setwd("/Users/jonghochoi/Documents/ECO")
getwd()
test <- read.table(file="tests.txt",header=TRUE,fill=TRUE, sep="|",quote="")
result <- read.table(file="results.txt",header=TRUE,fill=TRUE, sep="|",quote="")
dose_response <- read.table(file="dose_responses.txt",header=TRUE,fill=TRUE, sep="|",quote="")
dose_response_link <- read.table(file="dose_response_links.txt",header=TRUE,fill=TRUE, sep="|",quote="")
#head(dose_response)
#head(result)
#head(dose_response_link)
test_yes <- sort(subset(result, endpoint=="LC50" | endpoint=="LC50*" | endpoint=="EC50" | endpoint=="EC50*" )[,2])
head(test_yes)
